steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/app-image:$COMMIT_SHA", "."]

  # Step 2: Push Docker image to GCR
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/app-image:$COMMIT_SHA"]

  # Step 3: Deploy to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s-deployment.yaml
      - --image=gcr.io/$PROJECT_ID/app-image:$COMMIT_SHA
      - --location=us-central1
      - --cluster=my-gke-cluster

images:
  - "gcr.io/$PROJECT_ID/app-image:$COMMIT_SHA"
